### ISSUE TITLE
[Bug]: Code Blocks completely broken

### ISSUE THREAD

**Issue by FurociousFeline** [carlonicora/obsidian-rpg-manager#323]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Creating new element creates a new page with RPG manager UI 

### Current behaviour

opens an empty new tab, creates an unlinked page, said page has code block text when highlighted but doesn't display anything.
same issue persists wether I create an element using the campiagn page UI, RPG manager side bar, or using the terminal to execute the create x command.

Already Created elements still display properly but anything new is broken regardless of type

![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/152046086/5d2fc7c9-4f14-4182-b928-15ea9f03796a)

![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/152046086/dcbd0629-2af2-4fa9-8b81-097fc81dc49e)

### Reproduction

1. Create new campaign using sidebar
2. Edit title of campaign doc
3. Create a second campaign
4. Create an Adventure within first Campaign
5. 2nd campaign is displays simply as a code block when highlighted, but does not render the UI as expected
 * for some reason after a restart the 2nd campaign started to render properly, but this hasn't worked for any subsequent elements or restarts

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.4.16

### Plugin Version

4.1.4

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by FurociousFeline** [comment]
Update: did some more testing with Dev console open, for some reason having auto note mover enabled at all causes the code blocks to break and for no link to be generated between campaign>Adventure etc .... even if there are no rules set in that plugin?

when you reload with plugin disabled the previously broken pages will render correctly and new ones will as well, re enabling the plugin will make prexisting pages render properly but any new ones will be broken as described above

creating new element with rpg manager while auto note mover is enabled generates like a dozen errors all of this kind 
![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/152046086/7ac7f770-d778-4175-9ee2-4ba50456d05a)



`Uncaught TypeError: Cannot read properties of null (reading 'frontmatter')
    at isFmDisable (plugin:auto-note-mover:1806:68)
    at fileCheck (plugin:auto-note-mover:2079:13)
    at eval (plugin:auto-note-mover:2125:66)
    at e.tryTrigger (app.js:1:695499)
    at e.trigger (app.js:1:695432)
    at t.trigger (app.js:1:713365)
    at t.onChange (app.js:1:703609)
    at e.trigger (app.js:1:610660)
    at e.<anonymous> (app.js:1:608732)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at app.js:1:236048
    at new Promise (<anonymous>)
    at v (app.js:1:235793)
    at e.reconcileFileCreation (app.js:1:608209)
    at e.<anonymous> (app.js:1:607850)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at a (app.js:1:235850)
isFmDisable @ plugin:auto-note-mover:1806
fileCheck @ plugin:auto-note-mover:2079
eval @ plugin:auto-note-mover:2125
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
t.onChange @ app.js:1
e.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.reconcileFileCreation @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
setTimeout (async)
e.tryTrigger @ app.js:1
e.trigger @ app.js:1
t.trigger @ app.js:1
t.onChange @ app.js:1
e.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.reconcileFileCreation @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.reconcileFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.reconcileFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.reconcileInternalFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
(anonymous) @ app.js:1
n @ app.js:1
Promise.then (async)
e.queue @ app.js:1
e.write @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.create @ app.js:1
eval @ plugin:rpg-manager:84142
fulfilled @ plugin:rpg-manager:61
Promise.then (async)
step @ plugin:rpg-manager:73
eval @ plugin:rpg-manager:74
__async @ plugin:rpg-manager:58
create @ plugin:rpg-manager:84134
eval @ plugin:rpg-manager:84287
eval @ plugin:rpg-manager:74
__async @ plugin:rpg-manager:58
handleCreateNewChild @ plugin:rpg-manager:84281
callCallback2 @ plugin:rpg-manager:10754
invokeGuardedCallbackDev @ plugin:rpg-manager:10779
invokeGuardedCallback @ plugin:rpg-manager:10813
invokeGuardedCallbackAndCatchFirstError @ plugin:rpg-manager:10816
executeDispatch @ plugin:rpg-manager:13851
processDispatchQueueItemsInOrder @ plugin:rpg-manager:13871
processDispatchQueue @ plugin:rpg-manager:13880
dispatchEventsForPlugins @ plugin:rpg-manager:13888
eval @ plugin:rpg-manager:14012
batchedUpdates$1 @ plugin:rpg-manager:25484
batchedUpdates @ plugin:rpg-manager:10659
dispatchEventForPluginEventSystem @ plugin:rpg-manager:14011
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ plugin:rpg-manager:12342
dispatchEvent @ plugin:rpg-manager:12336
dispatchDiscreteEvent @ plugin:rpg-manager:12313
`

**Comment by carlonicora** [comment]
@FurociousFeline can you please update to the latest version (_I have released 4.1.6_) and show me what happens in the Inspector Console?

Thanks

**Comment by jupiterb4dawn** [comment]
Hello, I'm not OP but am having a similar problem where it seems like the auto-mover broke everything? Let me know if I should make a separate issue for this. 
This is the console when I try to make a new campaign (After deleting the original broken vault and starting a fresh one with the auto-mover off). Please let me know if I can get you any more useful info. 
![image](https://github.com/carlonicora/obsidian-rpg-manager/assets/46407627/8f0aa3bc-5231-4690-867f-83d05dc8369d)

**Comment by andy-mcbeer** [comment]
I'm getting this same issue, almost at random-- I'm synched across 3 devices and it seems like which notes will have broken code is almost random. Sometimes it fixes when I reload, sometimes it stays broken till I delete the note and make it all over again.
